export const CU_LIST_SUCCESS = 'CU_LIST';
export const CU_LIST_FAILURE = 'CU_LIST_FAILURE';
export const U_LIST_REQUEST = "U_LIST_REQUEST";
export const CU_LIST_ADD_SUCCESS = "CU_LIST_ADD_SUCCESS";
export const CU_LIST_ADD_FAILURE = "CU_LIST_ADD_FAILURE";
export const CU_LIST_ADD_REQUEST = "CU_LIST_ADD_REQUEST";
